ui/dialogs.d: fix build error due to missing 'sort'
This error occurs on Linux with ldc and dmd.

src/ui/dialogs.d(411): Error: no property 'sort' for type 'char[][]'